"use client";

import React from "react";
import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, Flame, Gauge, MoveUpRight, Route, Trophy, Waves } from "lucide-react";
import { PricingSection } from "@/frontend/components/pricing";

function enterApp(mode: "login" | "register") {
  window.location.assign(mode === "register" ? "/?mode=register" : "/");
}

export default function LandingPage(): React.JSX.Element {
  return <main className="landing-shell min-h-screen overflow-hidden bg-[#10110e] text-[#f4f2e8]">
    <header className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-9 lg:px-14">
      <a href="#inicio" aria-label="Vida Ativa Flex, início" className="flex items-center gap-2.5"><Image src="/logo-symbol.svg" alt="" width={36} height={36} priority /><span className="text-[13px] font-black leading-[.95] tracking-[-.04em]">VIDA ATIVA<br /><span className="text-[#d9f36b]">FLEX</span></span></a>
      <nav aria-label="Navegação principal" className="hidden items-center gap-8 text-[11px] font-bold uppercase tracking-[.15em] text-white/55 md:flex"><a className="transition hover:text-white" href="#metodo">O método</a><a className="transition hover:text-white" href="#recursos">Recursos</a><a className="transition hover:text-white" href="#planos">Planos</a><a className="transition hover:text-white" href="#sobre">Sobre</a></nav>
      <div className="flex items-center gap-3"><button onClick={() => enterApp("login")} className="hidden px-3 py-2 text-xs font-bold text-white/70 transition hover:text-white sm:block">Entrar</button><button onClick={() => enterApp("register")} className="group inline-flex items-center gap-2 rounded-full bg-[#d9f36b] px-4 py-2.5 text-[11px] font-black uppercase tracking-[.08em] text-[#151710] transition hover:bg-white sm:px-5">Começar agora <ArrowUpRight className="size-3.5 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button></div>
    </header>

    <section id="inicio" className="relative mx-auto grid max-w-[1440px] items-center gap-12 px-5 pb-20 pt-12 sm:px-9 sm:pb-24 lg:min-h-[690px] lg:grid-cols-[.95fr_1.05fr] lg:gap-8 lg:px-14 lg:pb-28 lg:pt-14">
      <div className="landing-orbit pointer-events-none absolute -left-40 top-12 size-[480px] rounded-full border border-white/[.045] sm:size-[620px]" />
      <div className="relative z-10 max-w-[650px]"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-3 py-2 text-[9px] font-black uppercase tracking-[.19em] text-white/65"><span className="size-1.5 rounded-full bg-[#d9f36b] shadow-[0_0_12px_#d9f36b]" /> Corrida com método. Vida sem pausa.</div>
        <h1 className="landing-title max-w-[780px] text-[clamp(3.6rem,9vw,7.8rem)] font-black uppercase leading-[.83] tracking-[-.085em]">Seu ritmo.<br /><span className="landing-outline">Sua rotina.</span><br /><span className="text-[#d9f36b]">Sua evolução.</span></h1>
        <div className="mt-8 flex flex-col gap-7 sm:flex-row sm:items-end sm:gap-12"><p className="max-w-[360px] text-sm leading-6 text-white/55 sm:text-[15px] sm:leading-7">Um plano de corrida feito para caber na vida real. Treinos flexíveis, ritmos personalizados e uma evolução que respeita o seu momento.</p><button onClick={() => enterApp("register")} className="group flex shrink-0 items-center gap-3 text-xs font-black uppercase tracking-[.12em] text-[#d9f36b]">Quero começar <span className="grid size-11 place-items-center rounded-full border border-[#d9f36b]/35 transition group-hover:bg-[#d9f36b] group-hover:text-black"><ArrowRight className="size-4 transition group-hover:translate-x-0.5" /></span></button></div>
        <div className="mt-12 flex items-center gap-4 text-[9px] font-bold uppercase tracking-[.17em] text-white/35"><span className="grid size-8 place-items-center rounded-full border border-white/10"><ArrowDown className="size-3" /></span> Desça para conhecer a FLEX</div>
      </div>
      <div className="landing-stage relative mx-auto w-full max-w-[670px] lg:ml-auto"><div className="pointer-events-none absolute left-[23%] top-[14%] size-[65%] rounded-full bg-[#d9f36b]/10 blur-[100px]" /><div className="landing-sun absolute right-[9%] top-0 aspect-square w-[40%] rounded-full border border-[#d9f36b]/25 bg-[radial-gradient(circle_at_38%_32%,rgba(217,243,107,.25),rgba(217,243,107,.025)_55%,transparent_72%)]" /><div className="absolute inset-x-[8%] bottom-[2%] top-[22%] rounded-[50%] border border-dashed border-[#d9f36b]/25 [transform:rotate(-24deg)]" />
        <div className="relative z-10 ml-auto w-[88%] translate-y-2 rotate-[2deg] rounded-[1.65rem] border border-white/10 bg-[#1a1c17]/95 p-3 shadow-[0_35px_110px_rgba(0,0,0,.6)] sm:w-[82%] sm:rounded-[2rem] sm:p-4"><div className="flex items-center justify-between border-b border-white/[.07] px-2 pb-3 sm:px-3 sm:pb-4"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#d9f36b]" /><span className="text-[9px] font-black uppercase tracking-[.18em] text-white/65">Prévia do app</span></div><span className="text-[9px] text-white/35">SEU PLANO</span></div>
          <div className="grid grid-cols-[1.2fr_.8fr] gap-2.5 pt-3 sm:gap-3 sm:pt-4"><div className="col-span-2 rounded-2xl bg-[#d9f36b] p-4 text-[#171910] sm:p-5"><div className="flex items-start justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.16em] opacity-55">Plano da semana</p><p className="mt-2 text-[clamp(1.5rem,4vw,2.6rem)] font-black leading-none tracking-[-.08em]">Feito para você.</p></div><MoveUpRight className="size-4" /></div><div className="mt-5 flex items-end justify-between"><div className="flex -space-x-1.5">{[1,2,3].map((n)=><span key={n} className={`grid size-7 place-items-center rounded-full border-2 border-[#d9f36b] text-[9px] font-black ${n===1?"bg-[#151710] text-[#d9f36b]":"bg-white/50 text-black/60"}`}>{n===1?<Check className="size-3" />:`0${n}`}</span>)}</div><p className="text-[9px] font-bold opacity-60">3 sessões · no seu tempo</p></div></div>
            <div className="relative min-h-[135px] overflow-hidden rounded-2xl bg-[#25271f] p-4 sm:min-h-[165px] sm:p-5"><div className="absolute -bottom-9 -right-7 size-32 rounded-full border border-[#d9f36b]/20" /><div className="relative flex items-center justify-between"><p className="text-[8px] font-black uppercase tracking-[.15em] text-white/45">Ritmo base · Z2</p><Gauge className="size-3.5 text-[#d9f36b]" /></div><p className="relative mt-7 text-[clamp(1.8rem,5vw,3rem)] font-black leading-none tracking-[-.08em]">06<span className="text-[.55em]">:20</span></p><p className="relative mt-1 text-[8px] font-bold uppercase tracking-[.13em] text-white/40">min / km</p></div>
            <div className="flex min-h-[135px] flex-col justify-between rounded-2xl border border-white/[.07] bg-[#13140f] p-4 sm:min-h-[165px] sm:p-5"><div className="flex items-center justify-between"><p className="text-[8px] font-black uppercase tracking-[.15em] text-white/45">Sua consistência</p><span className="text-[8px] font-bold text-[#d9f36b]">SESSÕES</span></div><div className="flex h-12 items-end gap-1.5 sm:h-16">{[30,43,36,55,48,72,64,91,73,100,82,100].map((h,i)=><span key={i} className="flex-1 rounded-t-sm bg-[#d9f36b]" style={{height:`${h}%`,opacity:.34+i/18}} />)}</div><p className="text-[8px] font-bold text-white/40">Consistência que vira resultado</p></div></div>
        </div><div className="landing-float absolute -left-1 bottom-[8%] z-20 flex items-center gap-3 rounded-2xl border border-white/10 bg-[#20221b] p-3 shadow-2xl sm:-left-3 sm:p-4"><div className="grid size-9 place-items-center rounded-xl bg-[#d9f36b] text-black"><Flame className="size-4" /></div><div><p className="text-[8px] font-black uppercase tracking-[.12em] text-white/40">Ritmo sustentável</p><p className="mt-1 text-[11px] font-black">Evoluir também é saber dosar.</p></div></div>
      </div>
    </section>

    <section className="border-y border-white/[.08] bg-[#d9f36b] text-[#151710]"><div className="mx-auto grid max-w-[1440px] grid-cols-2 divide-x divide-black/15 sm:grid-cols-4">{[{n:"01",t:"Plano que se adapta"},{n:"07",t:"Zonas de ritmo"},{n:"03",t:"Sessões por semana"},{n:"∞",t:"Seu próprio caminho"}].map((item)=><div key={item.n} className="px-5 py-5 sm:px-8 sm:py-6 lg:px-14"><p className="text-2xl font-black leading-none tracking-[-.07em] sm:text-3xl">{item.n}</p><p className="mt-2 text-[8px] font-black uppercase tracking-[.13em] opacity-60 sm:text-[9px]">{item.t}</p></div>)}</div></section>

    <section id="metodo" className="mx-auto grid max-w-[1440px] gap-12 px-5 py-24 sm:px-9 sm:py-32 lg:grid-cols-[.8fr_1.2fr] lg:gap-24 lg:px-14"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#d9f36b]">01 / Um método mais humano</p><h2 className="landing-title mt-6 text-5xl font-black uppercase leading-[.9] tracking-[-.075em] sm:text-7xl">Treinar bem<br />é <span className="landing-outline">continuar.</span></h2><p className="mt-7 max-w-sm text-sm leading-7 text-white/50">A rotina muda. Seu treino pode acompanhar. Na FLEX, consistência não depende de uma agenda perfeita — ela começa com o próximo passo possível.</p><button onClick={()=>enterApp("register")} className="mt-8 inline-flex items-center gap-2 border-b border-[#d9f36b]/45 pb-2 text-[10px] font-black uppercase tracking-[.15em] text-[#d9f36b] transition hover:border-[#d9f36b]">Conheça a FLEX <ArrowRight className="size-3.5" /></button></div>
      <div className="grid gap-3 sm:grid-cols-2"><article className="group relative min-h-[230px] overflow-hidden rounded-[1.35rem] border border-white/[.08] bg-[#1b1d17] p-6 sm:min-h-[290px] sm:p-8"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-white/[.06] text-[#d9f36b]"><Clock3 className="size-4" /></span><span className="text-[9px] font-black tracking-[.16em] text-white/30">01</span></div><h3 className="mt-9 max-w-[230px] text-2xl font-black leading-[.98] tracking-[-.05em] sm:text-[1.7rem]">Flexibilidade que faz sentido.</h3><p className="mt-3 max-w-[270px] text-xs leading-5 text-white/45">Três sessões para distribuir na semana. Você escolhe os dias, o plano dá a direção.</p><div className="absolute -bottom-10 -right-8 size-36 rounded-full border border-[#d9f36b]/15 transition group-hover:scale-110" /></article>
        <article className="group relative min-h-[230px] overflow-hidden rounded-[1.35rem] border border-white/[.08] bg-[#d9f36b] p-6 text-[#171910] sm:mt-12 sm:min-h-[290px] sm:p-8"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-black/[.08]"><Gauge className="size-4" /></span><span className="text-[9px] font-black tracking-[.16em] opacity-35">02</span></div><h3 className="mt-9 max-w-[230px] text-2xl font-black leading-[.98] tracking-[-.05em] sm:text-[1.7rem]">Seu esforço, na medida.</h3><p className="mt-3 max-w-[270px] text-xs leading-5 opacity-65">Um teste de 3 km ajuda a calcular zonas para você correr com intenção em cada treino.</p><div className="absolute -bottom-8 -right-6 size-32 rounded-full border border-black/10 transition group-hover:scale-110" /></article>
        <article className="group relative min-h-[230px] overflow-hidden rounded-[1.35rem] border border-white/[.08] bg-[#25271f] p-6 sm:min-h-[260px] sm:p-8"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-white/[.06] text-[#d9f36b]"><Waves className="size-4" /></span><span className="text-[9px] font-black tracking-[.16em] text-white/30">03</span></div><h3 className="mt-9 max-w-[240px] text-2xl font-black leading-[.98] tracking-[-.05em] sm:text-[1.7rem]">Da corrida para sua evolução.</h3><p className="mt-3 max-w-[280px] text-xs leading-5 text-white/45">Conecte o Strava para registrar atividades e acompanhar o caminho percorrido.</p></article>
        <article className="group relative min-h-[230px] overflow-hidden rounded-[1.35rem] border border-white/[.08] bg-[#171812] p-6 sm:mt-[-2rem] sm:min-h-[260px] sm:p-8"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-white/[.06] text-[#d9f36b]"><Trophy className="size-4" /></span><span className="text-[9px] font-black tracking-[.16em] text-white/30">04</span></div><h3 className="mt-9 max-w-[240px] text-2xl font-black leading-[.98] tracking-[-.05em] sm:text-[1.7rem]">Cada conquista conta.</h3><p className="mt-3 max-w-[280px] text-xs leading-5 text-white/45">Guarde tempos, provas e recordes pessoais. Sua história também faz parte do treino.</p></article></div>
    </section>

    <section id="recursos" className="relative overflow-hidden border-y border-white/[.07] bg-[#171812]"><div className="landing-grid absolute inset-0 opacity-40" /><div className="relative mx-auto grid max-w-[1440px] items-center gap-12 px-5 py-20 sm:px-9 sm:py-28 lg:grid-cols-[1fr_.9fr] lg:gap-24 lg:px-14"><div className="relative mx-auto w-full max-w-[490px]"><div className="relative mx-auto w-[min(76%,310px)] rounded-[2.3rem] border border-white/15 bg-[#090a08] p-2.5 shadow-[0_25px_100px_rgba(0,0,0,.6)]"><div className="rounded-[1.8rem] bg-[#171812] px-5 pb-6 pt-8"><div className="mx-auto mb-8 h-1 w-12 rounded-full bg-white/15" /><p className="text-[8px] font-black uppercase tracking-[.17em] text-[#d9f36b]">Exemplo de treino</p><h3 className="mt-3 text-3xl font-black leading-[.92] tracking-[-.07em]">Rodagem<br />leve</h3><div className="mt-6 flex items-center gap-3 border-y border-white/[.07] py-4"><span className="grid size-9 place-items-center rounded-full bg-[#d9f36b]/10 text-[#d9f36b]"><Route className="size-4" /></span><div><p className="text-[9px] font-black">40 minutos</p><p className="mt-1 text-[8px] text-white/40">Zona 2 · ritmo confortável</p></div></div><div className="mt-5 rounded-xl bg-[#24261f] p-4"><div className="flex justify-between text-[8px] font-bold text-white/45"><span>SEU PACE ALVO</span><span className="text-[#d9f36b]">Z2</span></div><p className="mt-2 text-2xl font-black tracking-[-.06em]">06:10 — 06:40 <span className="text-[9px] font-bold text-white/40">/km</span></p><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[42%] rounded-full bg-[#d9f36b]" /></div></div><div className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d9f36b] py-3 text-[9px] font-black uppercase tracking-[.12em] text-black">Marcar como feito <Check className="size-3" /></div></div></div><div className="absolute -right-2 top-[23%] rounded-xl border border-white/10 bg-[#25271f] px-3 py-2.5 shadow-xl sm:-right-5"><p className="text-[8px] font-black uppercase tracking-[.13em] text-white/40">Ritmo com propósito</p><p className="mt-1 text-xs font-black text-[#d9f36b]">Cada km no seu tempo.</p></div></div>
      <div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#d9f36b]">02 / Tudo em um só lugar</p><h2 className="landing-title mt-6 text-5xl font-black uppercase leading-[.88] tracking-[-.075em] sm:text-7xl">Menos dúvida.<br /><span className="landing-outline">Mais corrida.</span></h2><p className="mt-7 max-w-md text-sm leading-7 text-white/50">Abra seu treino e entenda o que fazer, em qual ritmo e por quê. A FLEX deixa o caminho claro para você só se preocupar com a próxima passada.</p><div className="mt-8 space-y-3">{["Plano semanal organizado por sessões", "Sete zonas de ritmo personalizadas", "Histórico de treinos e provas", "Integração com Strava"].map((item)=><p key={item} className="flex items-center gap-3 text-xs font-semibold text-white/70"><span className="grid size-5 place-items-center rounded-full bg-[#d9f36b]/10 text-[#d9f36b]"><Check className="size-3" /></span>{item}</p>)}</div></div></div></section>

    <PricingSection id="planos" className="border-t border-white/[.07] bg-[#12130e]" />

    <section id="sobre" className="mx-auto max-w-[1440px] px-5 py-24 text-center sm:px-9 sm:py-32 lg:px-14"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#d9f36b]">03 / Vamos nessa?</p><h2 className="landing-title mx-auto mt-6 max-w-4xl text-5xl font-black uppercase leading-[.86] tracking-[-.08em] sm:text-7xl lg:text-[6.5rem]">A linha de partida<br />é <span className="text-[#d9f36b]">a sua vida real.</span></h2><p className="mx-auto mt-7 max-w-lg text-sm leading-7 text-white/50">Comece com o que você tem hoje. A próxima versão de você agradece.</p><button onClick={()=>enterApp("register")} className="group mt-9 inline-flex items-center gap-3 rounded-full bg-[#d9f36b] px-7 py-4 text-[11px] font-black uppercase tracking-[.12em] text-[#151710] transition hover:bg-white">Criar minha conta <ChevronRight className="size-4 transition group-hover:translate-x-1" /></button></section>
    <footer className="border-t border-white/[.08]"><div className="mx-auto flex max-w-[1440px] flex-col gap-5 px-5 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-9 lg:px-14"><a href="#inicio" className="flex items-center gap-2"><Image src="/logo-symbol.svg" alt="" width={25} height={25} /><span className="text-[9px] font-black uppercase tracking-[.12em]">Vida Ativa <span className="text-[#d9f36b]">Flex</span></span></a><p className="text-[9px] font-semibold text-white/35">Feito para correr junto com a sua vida.</p><div className="flex items-center gap-5"><a href="#planos" className="text-[9px] font-black uppercase tracking-[.13em] text-white/55 transition hover:text-white">Planos</a><button onClick={()=>enterApp("login")} className="text-[9px] font-black uppercase tracking-[.13em] text-white/55 transition hover:text-white">Entrar</button><a href="#inicio" aria-label="Voltar ao início" className="grid size-8 place-items-center rounded-full border border-white/10 text-white/55 transition hover:border-[#d9f36b]/50 hover:text-[#d9f36b]"><ArrowUpRight className="size-3.5" /></a></div></div></footer>
    <style jsx global>{`.landing-title{font-family:var(--font-inter),Inter,ui-sans-serif,system-ui,sans-serif}.landing-outline{color:transparent;-webkit-text-stroke:1px rgba(244,242,232,.75)}.landing-orbit{background:radial-gradient(circle at center,rgba(217,243,107,.035),transparent 62%)}.landing-sun{animation:landing-pulse 8s ease-in-out infinite alternate}.landing-stage{animation:landing-enter .9s cubic-bezier(.2,.8,.2,1) both}.landing-float{animation:landing-float 5s ease-in-out infinite}.landing-grid{background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(90deg,transparent,black 25%,black 75%,transparent)}@keyframes landing-pulse{from{transform:scale(.94);opacity:.65}to{transform:scale(1.06);opacity:1}}@keyframes landing-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@keyframes landing-enter{from{opacity:0;transform:translateY(20px) rotate(2deg)}to{opacity:1;transform:translateY(0) rotate(2deg)}}@media(prefers-reduced-motion:reduce){.landing-sun,.landing-stage,.landing-float{animation:none!important}}`}</style>
  </main>;
}
